# Generated by Django 4.0.1 on 2022-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('distance', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
