# Generated by Django 4.0.1 on 2022-01-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
